title: <p align="center">Dominik Janyga </p> 
logo: "/images/profile.png?raw=true"
description: I hold an MS in Business Informatics and am passionate about transforming data into actionable insights.
  <br><br>
  I enjoy uncovering patterns and building predictive models to drive business decisions. 

  <p align="center">
    <a href="pdf/resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/dominik-janyga/">
      <img src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" width="16" height="16" alt="LinkedIn"> LinkedIn
    </a> |
    <a href="https://github.com/dominikjanyga">
      <img src="https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" width="16" height="16" alt="GitHub"> GitHub
    </a>
  </p>

  
  
  #<p align="center">
  #<a href="pdf/resume.pdf">Resume</a> |
  #<a href="https://www.linkedin.com/in/dominik-janyga/">LinkedIn</a> |
  #<a href="https://github.com/dominikjanyga">GitHub</a>
  #</p>

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 
