title: <p align="center">Dominik Janyga </p> 
logo: "/images/profile.png?raw=true"
description: I hold an MS in Business Informatics and am passionate about transforming data into actionable insights. 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dominik-janyga/">LinkedIn</a> |
  <a href="https://github.com/dominikjanyga">GitHub</a>
  </p>

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 
