title: <p align="center">Dominik Janyga </p> 
logo: <img src="/images/600x600.jpg?raw=true" alt="Logo" class="profile-logo">
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dominik-janyga/">LinkedIn</a> |
  <a href="https://github.com/dominikjanyga">GitHub</a>
  </p>

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 
